// Code generated by goctl. DO NOT EDIT.
// Source: socket.proto

package broadcast

import (
	"context"

	"store-chat/rpc/socket/pb/socket"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BodyEvent         = socket.BodyEvent
	EventDataLogin    = socket.EventDataLogin
	EventDataNormal   = socket.EventDataNormal
	EventParamsLogin  = socket.EventParamsLogin
	EventParamsNormal = socket.EventParamsNormal
	ReqBroadcastMsg   = socket.ReqBroadcastMsg
	ReqPing           = socket.ReqPing
	ResPing           = socket.ResPing
	Result            = socket.Result

	Broadcast interface {
		BroadcastLogin(ctx context.Context, in *ReqBroadcastMsg, opts ...grpc.CallOption) (*Result, error)
		BroadcastNormal(ctx context.Context, in *ReqBroadcastMsg, opts ...grpc.CallOption) (*Result, error)
		BroadcastOut(ctx context.Context, in *ReqBroadcastMsg, opts ...grpc.CallOption) (*Result, error)
	}

	defaultBroadcast struct {
		cli zrpc.Client
	}
)

func NewBroadcast(cli zrpc.Client) Broadcast {
	return &defaultBroadcast{
		cli: cli,
	}
}

func (m *defaultBroadcast) BroadcastLogin(ctx context.Context, in *ReqBroadcastMsg, opts ...grpc.CallOption) (*Result, error) {
	client := socket.NewBroadcastClient(m.cli.Conn())
	return client.BroadcastLogin(ctx, in, opts...)
}

func (m *defaultBroadcast) BroadcastNormal(ctx context.Context, in *ReqBroadcastMsg, opts ...grpc.CallOption) (*Result, error) {
	client := socket.NewBroadcastClient(m.cli.Conn())
	return client.BroadcastNormal(ctx, in, opts...)
}

func (m *defaultBroadcast) BroadcastOut(ctx context.Context, in *ReqBroadcastMsg, opts ...grpc.CallOption) (*Result, error) {
	client := socket.NewBroadcastClient(m.cli.Conn())
	return client.BroadcastOut(ctx, in, opts...)
}
