// Code generated by goctl. DO NOT EDIT.
package types

type DataPageList struct {
	Total   int64       `json:"total"`
	Page    int64       `json:"page"`
	Limit   int64       `json:"limit"`
	Offset  int64       `json:"offset"`
	Current int64       `json:"current"`
	Rows    interface{} `json:"rows"`
}

type ReqList struct {
	Request
	Offset int `json:"offset,string" binding:"required,min=0,max=20"`
	Limit  int `json:"limit,string" binding:"required,min=0,max=20"`
}

type ReqLogin struct {
	Request
	AutoToken string `header:"autoToken"`
}

type ReqOut struct {
	Request
	AutoToken string `header:"autoToken"`
}

type Request struct {
	Version     string `json:"version" binding:"required"`
	RequestTime int64  `json:"requestTime,string" binding:"required"`
}

type Response struct {
	Modult       string      `json:"modult"`
	Code         string      `json:"code"`
	Message      string      `json:"message"`
	ResponseTime string      `json:"responseTime"`
	Data         interface{} `json:"data"`
}
