// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	user "store-chat/api/internal/handler/user"
	"store-chat/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/list",
				Handler: user.ListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AutoToken},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/user/login",
					Handler: user.LoginHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/users/out",
					Handler: user.OutHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1"),
	)
}
