// Code generated by goctl. DO NOT EDIT.
// Source: socket.proto

package server

import (
	"context"

	"store-chat/rpc/socket/internal/logic/ping"
	"store-chat/rpc/socket/internal/svc"
	"store-chat/rpc/socket/pb/socket"
)

type PingServer struct {
	svcCtx *svc.ServiceContext
	socket.UnimplementedPingServer
}

func NewPingServer(svcCtx *svc.ServiceContext) *PingServer {
	return &PingServer{
		svcCtx: svcCtx,
	}
}

func (s *PingServer) Ping(ctx context.Context, in *socket.ReqPing) (*socket.ResPing, error) {
	l := pinglogic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
