// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"
	servers "store-chat/socket/server"

	"store-chat/socket/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext, socket *servers.Server) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/test",
				Handler: TestHandler(serverCtx),
			},
			{
				// clint进行连接
				Method: http.MethodGet,
				Path:   "/ws",
				Handler: func(w http.ResponseWriter, r *http.Request) {
					servers.NewConnect().Run(w, r, socket)
				},
			},
		},
	)
}
